### ISSUE TITLE
Airflow integration

### ISSUE THREAD

**Issue by momegas** [squaredev-io/whitebox#84]

**Comment by momegas** [comment]
To start development You can use this compose that I made for some local tests.
Just place your dags in a dags folder in the root of the projects (or change the path in the volumes of  webserver to `./whitebox/dags:/usr/local/airflow/dags`)


```yaml
version: "3.7"

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./evidently_reports:/usr/local/airflow/reports
      - ./data:/usr/local/airflow/data
      - ./logs:/usr/local/airflow/logs
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  evidently_reports:

```
